[workspace]
resolver = "2"
members = [
    "day-01",
    "day-01/solver",
    "day-02",
]

[workspace.dependencies]
anyhow = "1.0.93"
wasmtime = { version = "27.0.0", features = ["component-model", "gc"] }
