package aoc:base;

interface day {
    resource runner {
        constructor(input: string);
        solve-a: func() -> string;
        solve-b: func() -> string;
    }
}

interface debug {
    info: func(input: string);
}

world day-world {
    export day;
    import debug;
}
